### ISSUE TITLE
连接设备问题

### ISSUE THREAD

**Issue by purecheeses** [openatx/atx-webide#31]
运行最新版的 atxweb 选择了设备之后点连接永远是连接失败 
错误信息：
2017-04-07 17:07:45.058 INFO  [webide: 413] Server started.
2017-04-07 17:07:45.059 INFO  [webide: 414] Listening port on 127.0.0.1:10010
WARNING:tornado.access:404 GET /${img.path} (127.0.0.1) 1.16ms
2017-04-07 17:07:45.571 INFO  [webide: 119] WebSocket connected
android device list: [u'571116ba']
ERROR:tornado.application:Uncaught exception POST /device (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:10010', method='POST', uri='/device', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Origin': 'http://127.0.0.1:10010', 'Content-Length': '7', 'Accept-Language': 'zh-cn', 'Accept-Encoding': 'gzip, deflate', 'Host': '127.0.0.1:10010', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50', 'Connection': 'keep-alive', 'Referer': 'http://127.0.0.1:10010/', 'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8'})
Traceback (most recent call last):
  File "/Users/happyelements/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1443, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/Users/happyelements/anaconda/lib/python2.7/site-packages/atxweb/server.py", line 343, in post
    device = atx.connect(**settings)
  File "/Users/happyelements/anaconda/lib/python2.7/site-packages/atx/__init__.py", line 77, in connect
    c = cls(connect_url, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'serialno'
ERROR:tornado.access:500 POST /device (127.0.0.1) 100.54ms

将atx 和webide的版本分别换成这两个才能运行：
 sudo pip install --pre atx-webide==0.1.1.dev58
 sudo pip install --pre atx==1.1.1.dev42

**Comment by ghost62184** [comment]
厉害了，你是自己试出来的吗

**Comment by ijasonyi** [comment]
出错的atxweb版本是多少，对应的atx呢

**Comment by lijiawei1** [comment]
厉害，应该是atx-1.1.3.dev4在win下有这个问题

**Comment by codeskyblue** [comment]
不是atx 的问题，是旧版的atxweb 不兼容

**Comment by liangliangludan** [comment]
我有出现相同的问题

**Comment by lxf920125** [comment]
这问题要搞死人啊
